# Generated by Django 5.2.5 on 2025-08-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Название ингредиента, например: 'Сахар', 'Молоко'", max_length=128)),
                ('measurement_unit', models.CharField(help_text="Единица измерения ингредиента, например: 'г', 'мл'", max_length=32)),
            ],
        ),
    ]
