# Пагинация
DEFAULT_PAGE_SIZE = 6
PAGE_SIZE_QUERY_PARAM = "limit"

# Пользователи
MAX_NAME_LENGTH = 150
MAX_USERNAME_LENGTH = 150
MAX_EMAIL_LENGTH = 254

# Ограничения по ингредиентам и рецептам
MIN_INGREDIENT_AMOUNT = 1
MIN_COOKING_TIME = 1

# Ингредиенты
MAX_INGREDIENT_NAME_LENGTH = 128
MAX_MEASUREMENT_UNIT_LENGTH = 32

# Теги
MAX_TAG_NAME_LENGTH = 32
MAX_TAG_SLUG_LENGTH = 32

# Рецепты
MAX_RECIPE_NAME_LENGTH = 200
