# Generated by Django 5.2.5 on 2025-08-27 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_name_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='slug тега', max_length=32, unique=True),
        ),
    ]
