# Generated by Django 5.2.5 on 2025-09-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Название ингредиента, например: 'Сахар', 'Молоко'", max_length=128)),
                ('measurement_unit', models.CharField(help_text="Единица измерения ингредиента, например: 'г', 'мл'", max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название рецепта', max_length=200)),
                ('image', models.ImageField(help_text='Фото блюда', upload_to='recipes/images/')),
                ('text', models.TextField(help_text='Описание рецепта')),
                ('cooking_time', models.PositiveIntegerField(help_text='Время приготовления в минутах')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(help_text='Количество ингредиента в рецепте')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название тега', max_length=32, unique=True)),
                ('slug', models.SlugField(help_text='slug тега', max_length=32, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
