# Generated by Django 5.2.5 on 2025-09-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(help_text='Фото блюда', upload_to='recipes/'),
        ),
    ]
