# Generated by Django 5.2.5 on 2025-08-29 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('recipes', '0002_alter_recipeingredient_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(help_text='Ингредиент рецепта', on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(help_text='Ингредиенты', related_name='recipes', through='recipes.RecipeIngredient', to='ingredients.ingredient'),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
